man(timo).
man(john).
man(peter).
woman(helen).
woman(kate).
beautiful(helen).
beautiful(john).
rich(john).
rich(peter).
strong(peter).
strong(timo).
kind(timo).
likes(X,Y):-man(X),woman(Y),beautiful(Y).
likes(helen,X):-man(X),((rich(X),kind(X))|(strong(X),beautiful(X))).
likes(kate,X):-man(X),likes(X,kate).
happy(X):-rich(X).
happy(X):-man(X),likes(X,Y),woman(Y),likes(Y,X).
happy(X):-woman(X),likes(X,Y),man(Y),likes(Y,X).
